import type { ClientRow, LeadRow, ProspectRow, WaitingListRow } from './types';

/**
 * Static sample rows mirroring the designers' screenshots. Structured so real
 * API data drops into the same tables as props without layout changes.
 */

export const LEADS: LeadRow[] = [
  {
    id: 'l1',
    name: 'Emma Johnson',
    phone: '(313) 555-0122',
    email: 'emma.johnson@gmail.com',
    source: 'Website',
    status: { label: 'Invite Sent', tone: 'success' },
    createdBy: 'Sarah Kim',
    createdOn: '9:38 AM, 07-15-26',
  },
  {
    id: 'l2',
    name: 'James Carter',
    phone: '(415) 555-0167',
    email: 'james.carter@outlook.com',
    source: 'Walk In',
    status: { label: 'Invite Sent', tone: 'success' },
    createdBy: 'Mark Wood',
    createdOn: '10:15 AM, 01-06-26',
  },
  {
    id: 'l3',
    name: 'Olivia Martinez',
    phone: '(212) 555-0341',
    email: 'olivia.m@yahoo.com',
    source: 'Phone Call',
    status: { label: 'Invite Sent', tone: 'success' },
    createdBy: 'Sarah Kim',
    createdOn: '2:45 PM, 01-07-26',
  },
  {
    id: 'l4',
    name: 'Liam Thompson',
    phone: '(713) 555-0922',
    email: 'l.thompson@gmail.com',
    source: 'Email',
    status: { label: 'Invite Sent', tone: 'success' },
    createdBy: 'James Porter',
    createdOn: '11:00 AM, 01-08-26',
  },
  {
    id: 'l5',
    name: 'Sophia Davis',
    phone: '(305) 555-0676',
    email: 'sophia.davis@hotmail.com',
    source: 'Regional Centre',
    status: { label: 'Invite Sent', tone: 'success' },
    createdBy: 'Mark Wood',
    createdOn: '3:24 PM, 01-09-26',
  },
  {
    id: 'l6',
    name: 'Noah Wilson',
    phone: '(404) 555-0479',
    email: 'noah.wilson@gmail.com',
    source: 'Website',
    status: { label: 'Invite Sent', tone: 'success' },
    createdBy: 'Lisa Chen',
    createdOn: '8:55 AM, 01-12-26',
  },
  {
    id: 'l7',
    name: 'Isabella Brown',
    phone: '(602) 555-0932',
    email: 'i.brown@outlook.com',
    source: 'Website',
    status: { label: 'Invite Sent', tone: 'success' },
    createdBy: 'James Porter',
    createdOn: '1:12 PM, 01-13-26',
  },
  {
    id: 'l8',
    name: 'William Garcia',
    phone: '(602) 555-0148',
    email: 'w.garcia@gmail.com',
    source: 'Regional Centre',
    status: { label: 'Invite Sent', tone: 'success' },
    createdBy: 'Mark Wood',
    createdOn: '4:00 PM, 01-13-26',
  },
  {
    id: 'l9',
    name: 'Mia Anderson',
    phone: '(206) 555-0517',
    email: 'mia.anderson@yahoo.com',
    source: 'Walk In',
    status: { label: 'Invite Sent', tone: 'success' },
    createdBy: 'Sarah Kim',
    createdOn: '9:15 AM, 01-14-26',
  },
  {
    id: 'l10',
    name: 'Benjamin Lee',
    phone: '(312) 555-0361',
    email: 'b.lee@gmail.com',
    source: 'Phone Call',
    status: { label: 'Invite Sent', tone: 'success' },
    createdBy: 'Lisa Chen',
    createdOn: '11:45 AM, 01-15-26',
  },
];

export const PROSPECTS: ProspectRow[] = [
  {
    id: 'p1',
    name: 'Julian Flores',
    phone: '(305) 555-6795',
    email: 'julian.flores@example.com',
    language: 'English',
    source: 'Intake Form',
    paymentSource: 'Regional Center',
    status: { label: 'Trial Pending', tone: 'neutral' },
  },
  {
    id: 'p2',
    name: 'Ethan Haddad',
    phone: '(213) 555-3153',
    email: 'ethan.haddad@example.com',
    language: 'English',
    source: 'Intake Form',
    paymentSource: 'Self Pay',
    status: { label: 'Trial Pending', tone: 'neutral' },
  },
  {
    id: 'p3',
    name: 'Mateo Díaz',
    phone: '(305) 555-0188',
    email: 'mateo.diaz@example.com',
    language: 'Spanish',
    source: 'Regional Centre',
    paymentSource: 'Regional Center',
    status: { label: 'Trial Scheduled', tone: 'neutral' },
  },
  {
    id: 'p4',
    name: 'Sofía Herrera',
    phone: '(305) 555-0155',
    email: 'sofia.herrera@example.com',
    language: 'Spanish',
    source: 'Regional Centre',
    paymentSource: 'Self Determination',
    status: { label: 'Trial Completed', tone: 'info', dropdown: true },
  },
  {
    id: 'p5',
    name: 'Olivia Bennett',
    phone: '(818) 555-0164',
    email: 'olivia.bennett@example.com',
    language: 'English',
    source: 'Website',
    paymentSource: 'Regional Center',
    status: { label: 'Trial Completed', tone: 'info', dropdown: true },
  },
  {
    id: 'p6',
    name: 'Valentina Rossi',
    phone: '(305) 555-0147',
    email: 'valentina.rossi@example.com',
    language: 'Spanish',
    source: 'Website',
    paymentSource: 'Self Pay',
    status: { label: 'Trial Completed', tone: 'info' },
  },
  {
    id: 'p7',
    name: 'Lucas Fernández',
    phone: '(213) 555-0137',
    email: 'lucas.fernandez@example.com',
    language: 'Spanish',
    source: 'Walk In',
    paymentSource: 'Regional Center',
    status: { label: 'Authorization Sent', tone: 'warning', dropdown: true },
  },
];

export const WAITING_LIST: WaitingListRow[] = [
  {
    id: 'w1',
    name: 'Amara Okafor',
    phone: '(626) 555-0119',
    email: 'amara.okafor@example.com',
    language: 'English',
    source: 'Phone Call',
    paymentSource: 'Regional Center',
    status: { label: 'Ready to Schedule', tone: 'success' },
  },
  {
    id: 'w2',
    name: 'Ethan Rivera',
    phone: '(786) 555-0182',
    email: 'ethan.rivera@example.com',
    language: 'English',
    source: 'Website',
    paymentSource: 'Self Pay',
    status: { label: 'Ready to Schedule', tone: 'success' },
  },
  {
    id: 'w3',
    name: 'Grace Reyes',
    phone: '(305) 555-1100',
    email: 'grace.reyes0@example.com',
    language: 'English',
    source: 'Website',
    paymentSource: 'Regional Center',
    status: { label: 'Ready to Schedule', tone: 'success' },
  },
  {
    id: 'w4',
    name: 'Owen Garcia',
    phone: '(786) 555-1101',
    email: 'owen.garcia1@example.com',
    language: 'English',
    source: 'Walk In',
    paymentSource: 'Regional Center',
    status: { label: 'Ready to Schedule', tone: 'success' },
  },
  {
    id: 'w5',
    name: 'Aria Silva',
    phone: '(818) 555-1102',
    email: 'aria.silva2@example.com',
    language: 'Spanish',
    source: 'Phone Call',
    paymentSource: 'Regional Center',
    status: { label: 'Ready to Schedule', tone: 'success' },
  },
  {
    id: 'w6',
    name: 'Levi Rossi',
    phone: '(213) 555-1103',
    email: 'levi.rossi3@example.com',
    language: 'English',
    source: 'Regional Centre',
    paymentSource: 'Self Pay',
    status: { label: 'Ready to Schedule', tone: 'success' },
  },
  {
    id: 'w7',
    name: 'Nora Mendez',
    phone: '(626) 555-1104',
    email: 'nora.mendez4@example.com',
    language: 'English',
    source: 'Email',
    paymentSource: 'Self Determination',
    status: { label: 'Ready to Schedule', tone: 'success' },
  },
  {
    id: 'w8',
    name: 'Isaac Park',
    phone: '(305) 555-1105',
    email: 'isaac.park5@example.com',
    language: 'Spanish',
    source: 'Intake Form',
    paymentSource: 'Regional Center',
    status: { label: 'Ready to Schedule', tone: 'success' },
  },
  {
    id: 'w9',
    name: 'Layla Bauer',
    phone: '(786) 555-1106',
    email: 'layla.bauer6@example.com',
    language: 'English',
    source: 'Website',
    paymentSource: 'Regional Center',
    status: { label: 'Ready to Schedule', tone: 'success' },
  },
  {
    id: 'w10',
    name: 'Gabriel Nguyen',
    phone: '(818) 555-1107',
    email: 'gabriel.nguyen7@example.com',
    language: 'English',
    source: 'Walk In',
    paymentSource: 'Regional Center',
    status: { label: 'Ready to Schedule', tone: 'success' },
  },
];

export const CLIENTS: ClientRow[] = [
  {
    id: 'c1',
    name: 'Noah Williams',
    phone: '(305) 555-0100',
    email: 'noah.williams0@example.com',
    language: 'English',
    source: 'Website',
    program: 'Individual Music Therapy',
    condition: 'Autism Spectrum',
    communityCenter: 'Frank D. Lanterman RC',
    paymentSource: 'Regional Center',
    status: { label: 'Active', tone: 'success' },
  },
  {
    id: 'c2',
    name: 'Ava Herrera',
    phone: '(786) 555-0101',
    email: 'ava.herrera1@example.com',
    language: 'English',
    source: 'Walk In',
    program: 'Group Music Therapy',
    condition: 'Developmental Delay',
    communityCenter: 'North LA County RC',
    paymentSource: 'Regional Center',
    status: { label: 'Active', tone: 'success' },
  },
  {
    id: 'c3',
    name: 'Diego Nguyen',
    phone: '(818) 555-0102',
    email: 'diego.nguyen2@example.com',
    language: 'Spanish',
    source: 'Phone Call',
    program: 'Neurologic Music Therapy',
    condition: 'Anxiety / Stress',
    communityCenter: 'San Gabriel/Pomona RC',
    paymentSource: 'Regional Center',
    status: { label: 'Active', tone: 'success' },
  },
  {
    id: 'c4',
    name: 'Sofia Rivera',
    phone: '(213) 555-0103',
    email: 'sofia.rivera3@example.com',
    language: 'English',
    source: 'Regional Centre',
    program: 'Adaptive Music Lessons',
    condition: 'Stroke Recovery',
    communityCenter: 'Eastern LA RC',
    paymentSource: 'Self Pay',
    status: { label: 'Active', tone: 'success' },
  },
  {
    id: 'c5',
    name: 'James Kim',
    phone: '(626) 555-0104',
    email: 'james.kim4@example.com',
    language: 'English',
    source: 'Email',
    program: 'Music & Wellness',
    condition: 'Dementia',
    communityCenter: 'Frank D. Lanterman RC',
    paymentSource: 'Self Determination',
    status: { label: 'On Hold', tone: 'warning' },
  },
  {
    id: 'c6',
    name: 'Mateo Garcia',
    phone: '(305) 555-0105',
    email: 'mateo.garcia5@example.com',
    language: 'Spanish',
    source: 'Website',
    program: 'Individual Music Therapy',
    condition: 'Down Syndrome',
    communityCenter: 'North LA County RC',
    paymentSource: 'Regional Center',
    status: { label: 'On Hold', tone: 'warning' },
  },
  {
    id: 'c7',
    name: 'Emma Haddad',
    phone: '(786) 555-0106',
    email: 'emma.haddad6@example.com',
    language: 'English',
    source: 'Walk In',
    program: 'Group Music Therapy',
    condition: 'Other',
    communityCenter: 'San Gabriel/Pomona RC',
    paymentSource: 'Regional Center',
    status: { label: 'Active', tone: 'success' },
  },
  {
    id: 'c8',
    name: 'Lucia Thompson',
    phone: '(818) 555-0107',
    email: 'lucia.thompson7@example.com',
    language: 'English',
    source: 'Phone Call',
    program: 'Neurologic Music Therapy',
    condition: 'Autism Spectrum',
    communityCenter: 'Eastern LA RC',
    paymentSource: 'Regional Center',
    status: { label: 'Active', tone: 'success' },
  },
  {
    id: 'c9',
    name: 'Liam Carter',
    phone: '(213) 555-0108',
    email: 'liam.carter8@example.com',
    language: 'Spanish',
    source: 'Regional Centre',
    program: 'Adaptive Music Lessons',
    condition: 'Developmental Delay',
    communityCenter: 'Frank D. Lanterman RC',
    paymentSource: 'Self Pay',
    status: { label: 'Active', tone: 'success' },
  },
  {
    id: 'c10',
    name: 'Olivia Torres',
    phone: '(626) 555-0109',
    email: 'olivia.torres9@example.com',
    language: 'English',
    source: 'Email',
    program: 'Music & Wellness',
    condition: 'Anxiety / Stress',
    communityCenter: 'North LA County RC',
    paymentSource: 'Self Determination',
    status: { label: 'Active', tone: 'success' },
  },
];
